### ISSUE TITLE
SVFI 4.0 改用Electron UI

### ISSUE THREAD

**Issue by NULL204** [Justin62628/Squirrel-RIFE#115]
新Electron UI尽早提上日程
我不能再苟下去了

**Comment by Justin62628** [comment]
《你知道就好》/xyx

**Comment by YiWeiHuang-stack** [comment]
《你知道就好》/xyx

**Comment by NULL204** [comment]
参考资料
https://zhuanlan.zhihu.com/p/37999476?utm_source=qq&utm_medium=social&utm_oi=898883384397402112

**Comment by YiWeiHuang-stack** [comment]
你看看你还在玩原神/orz

**Comment by Justin62628** [comment]
计划在SVFI 3.5 上线Steam、维稳生态后着手开发工作

**Comment by Justin62628** [comment]
SVFI 3.21
