### ISSUE TITLE
多任务选中任务时醒目化

### ISSUE THREAD

**Issue by yhrbjsy** [Justin62628/Squirrel-RIFE#130]
![image](https://user-images.githubusercontent.com/59187833/129296759-bd55a3cb-58c8-4c84-8172-192f356b11e1.png)
如图，这个已选中也太不明显了。。。搞个对勾啥的吧
默认选中第一条任务（如果有的话），也能规避一些任务为空的bug

**Comment by Justin62628** [comment]
SVFI 3.5.7
