### ISSUE TITLE
社区版教程提醒

### ISSUE THREAD

**Issue by yhrbjsy** [Justin62628/Squirrel-RIFE#132]
考虑到上steam后用户很少看根目录，因此将教程放在根目录等用户自行阅读并不是个很好的选项了
建议在初次启动应用时弹窗提醒阅读教程
在主界面显示教程的链接，点击即可阅读（只需本地word/PDF链接均可），用户添加视频后再自行隐去
![屏幕截图 2021-08-13 175642](https://user-images.githubusercontent.com/59187833/129340094-9a9115bd-5683-404e-9d39-dde99e834a50.png)

**Comment by Justin62628** [comment]
SVFI 3.5.13
