### ISSUE TITLE
GPU编号识别错误

### ISSUE THREAD

**Issue by MAX-XiaoKui** [Justin62628/Squirrel-RIFE#154]
![image](https://user-images.githubusercontent.com/53287753/132117690-8e4477c2-fcdc-4249-ab2b-65ed87591424.png)
我选择1060的时候它用750Ti
当我选择750Ti的时候它会用1060
版本 3.2 Community

**Comment by Justin62628** [comment]
由截图知SVFI（强制）使用了A卡模式（因为用了rife-v3.0模型）
由于维护原因暂时不可获取A卡模式下的显卡列表，可手动在
![image](https://user-images.githubusercontent.com/37169106/132118173-c6532afc-d024-41ac-9473-6f9904125004.png)
调节使用的GPU
根据您提供的信息，
GPU 1（750）对应序号0
GPU 2（1060）对应序号1
在N卡模式下（使用CUDA），序号对应同上，但是由选项
![image](https://user-images.githubusercontent.com/37169106/132118225-d8ac685c-dde5-45ae-9a64-1678432d7290.png)
控制

**Comment by MAX-XiaoKui** [comment]
好谢谢
顺便问一下1080p，24fps x4，GTX1060这个速度正常吗
`Process at Chunk 001: 5%|5 | 315/5760 [01:51<33:15, 2.73frames/s, R=310, C=315, S=350, SC=8, TAT=0.64s, PT=0.92s, QL=0]`

**Comment by Justin62628** [comment]
> 好谢谢
> 顺便问一下4k，24fps x4，GTX1060这个速度正常吗
> `Process at Chunk 001: 5%|5 | 315/5760 [01:51<33:15, 2.73frames/s, R=310, C=315, S=350, SC=8, TAT=0.64s, PT=0.92s, QL=0]`

QL=0意味着CPU编码瓶颈，CPU跟不上补帧
