### ISSUE TITLE
程序运行时卡住

### ISSUE THREAD

**Issue by MAX-XiaoKui** [Justin62628/Squirrel-RIFE#155]
3.2 Community
处理视频时卡住，输出不动
任务管理器显示GPU占用为0
GPU-Z和AIDA64中显示GPU占用为100%，GPU内存控制器占用为0
GPU频率、显存频率、显存占用没有降
卡住一段时间后GPU频率、显存频率、显存占用都降下去，再往后可能会出现系统黑屏只有一个光标，然后掉超频，正在进行的操作（比如打字）在黑屏恢复后再进行的情况
试过重装显卡驱动（清洁安装），没多大作用
![image](https://user-images.githubusercontent.com/53287753/132128728-0ddec670-9d91-4d36-825e-a96708986d06.png)
![image](https://user-images.githubusercontent.com/53287753/132128773-1a5a85b1-3cde-4be5-b5cc-f50a1457b860.png)
![image](https://user-images.githubusercontent.com/53287753/132129647-f205ac83-5d5e-485f-883e-07293f636c8e.png)
[2021-09-05.error.log](https://github.com/Justin62628/Squirrel-RIFE/files/7111669/2021-09-05.error.log)
而且补帧时GPU会有一下没一下的占用：
![image](https://user-images.githubusercontent.com/53287753/132129528-371c1b6a-4525-4bd7-9457-50e2b2d44c1a.png)
之后我在`%LocalAppData%\CrashDumps`目录中发现了几个`one_line_shot_args.exe`的转储文件：
[CrashDumps.zip](https://github.com/Justin62628/Squirrel-RIFE/files/7111693/CrashDumps.zip)

**Comment by Justin62628** [comment]
明天Steam上线3.5版本，应该可以缓解你说的卡进程的问题

**Comment by MAX-XiaoKui** [comment]
已解决，应该是显卡频率太高导致的不稳定
