### ISSUE TITLE
结构：多任务优化

### ISSUE THREAD

**Issue by yhrbjsy** [Justin62628/Squirrel-RIFE#179]
![image](https://user-images.githubusercontent.com/59187833/133025040-7f3afeac-9fc2-4c8a-aaa6-b0008423dba6.png)
当有多个任务时，能选择与取消将要补帧率的任务，而非只能选择不能取消
原因：在部分任务进行到一半时，遇到新任务优先级更高，需要先补。那么就需要将新任务选中而旧任务不选中。

**Comment by Justin62628** [comment]
- [ ] 勾选任务完成后删除
- [ ] 补帧进行时自动添加第一个还在任务队列中且打勾的任务
- [ ] 如队列中只有一个任务（社区版/完成多任务后的专业版），完成后不删除任务

**Comment by Justin62628** [comment]
SVFI 3.5.20 局部优化了指定需求：
1. 能选择取消补帧任务

**Comment by Justin62628** [comment]
SVFI 3.7.7 局部优化完成，留待观察
