### ISSUE TITLE
VOB格式支持及合并后MKV文件无法播放的修复

### ISSUE THREAD

**Issue by yhrbjsy** [Justin62628/Squirrel-RIFE#180]
VOB格式样例已上传至内测群
补帧完成生成后的MKV文件往往不能由MPC-HC正常读取，需要重封装，当前推测是合并流后会生成额外的chapter，造成播放器读取异常。（下图为正常情况样例，合并流后的情况会在底下还多一至两行chapter)
![image](https://user-images.githubusercontent.com/59187833/133026179-390e0c7b-271b-4662-bf55-a32981287bd1.png)

**Comment by Justin62628** [comment]
懂了，这波直接不复制章节

**Comment by Justin62628** [comment]
SVFI 3.5.20 识别到输入为vob且输出为mkv时取消章节合并

**Comment by Justin62628** [comment]
SVFI 3.5.20
