### ISSUE TITLE
教程：加入对于显卡/CPU瓶颈的判断方法

### ISSUE THREAD

**Issue by yhrbjsy** [Justin62628/Squirrel-RIFE#182]
（1）如果发现自己硬盘占用时常100%，赶紧换硬盘吧，说明你硬盘快坏了
（2）QL值长期维持在10以下说明拆帧瓶颈，开启快拆或者更换单核性能更强的CPU
（3）TAT值长期不为0说明编码瓶颈，更换fast或ultrafast编码，或者更换性能更强的CPU。intel处理器在开启核显后可使用QSV
（4）TAT为0，且QL值稳定在较高的值，说明补帧的限制在显卡上，能最大程度榨干显卡的性能。
（5）对于30系显卡，有一定动手能力的可自行替换torch与torchvision。将群文件里文件解压至根目录对应文件夹替换即可。（先删除原文件夹里的文件），后续会上线30系显卡专用免费DLC。

**Comment by Justin62628** [comment]
SVFI 3.6.0
