### ISSUE TITLE
社区版预设优化

### ISSUE THREAD

**Issue by yhrbjsy** [Justin62628/Squirrel-RIFE#192]
1. H264全扔了吧，常规质量还是用的264
2. 光流尺度识别视频分辨率，对于实拍，2.3模型下 1080P给1.0, 4K给0.5
3. 极致速度和速度优先目前实拍也是3.6，换回3.8吧
4. 速度优先和常规质量的编码都更换为H265 10bit/8bit fast编码
5. 选择真人时，丝滑菜单置灰不可选

**Comment by Justin62628** [comment]
- [ ] 动漫丝滑控制栏添加“不去重”

**Comment by Justin62628** [comment]
SVFI 3.7.0
