### ISSUE TITLE
高 DPI 下 GUI 无法正常显示

### ISSUE THREAD

**Issue by Flyfish233** [Justin62628/Squirrel-RIFE#196]
**复现方式** 在 Windows 设置-显示中调整缩放为 100 以上。该问题对任何 GPU 都有效。

<img width="523" alt="系统缩放 150" src="https://user-images.githubusercontent.com/37693645/134027720-f80252cc-54d4-4157-9749-251fbe88ecc4.png">

**显示效果**

<img width="659" alt="屏幕截图" src="https://user-images.githubusercontent.com/37693645/134027732-71d63f6e-16bb-4b0d-88f1-66faf8f18038.png">

**解决方案** 经查看，您软件或使用了 Qt 作为图形化界面，以下是针对 Qt 的可行方案
[在 Qt5 和 PyQt5 中设置支持高分辨率屏幕自适应](https://blog.csdn.net/weixin_43323092/article/details/83905159)

**Comment by Justin62628** [comment]
下个版本会添加主控件（主窗口）的最小大小限制（960x720）
高分辨率屏幕自适应已在SVFI 3.5加入

**Comment by Justin62628** [comment]
SVFI 3.6.4
