### ISSUE TITLE
希望可以加入“完美循环的视频”功能，让补帧后的视频可以完美循环

### ISSUE THREAD

**Issue by 0Lynk** [Justin62628/Squirrel-RIFE#288]
有些视频是头尾相连，可以完美循环，一些其他补帧软件可以开启该选项以头尾两帧中间插入一帧，保证补帧后视频仍是完美循环。否则就会在循环时缺少一帧。
但是SVFI似乎没有这个功能。

**Comment by Justin62628** [comment]
以后会提供此选项

- [ ] UI
- [ ] OLS保存第一帧img00
- [ ] if img0 is none, feed(interpolate(img0, img00, n=1))

**Comment by Justin62628** [comment]
SVFI 3.21.9-alpha
