### ISSUE TITLE
软件无法打开

### ISSUE THREAD

**Issue by benzBrake** [Justin62628/Squirrel-RIFE#315]
Steam 上的  SVFI
电脑是 10105f +560xt
打开软件显示无N卡，将使用核显或A卡，点击确定就退出了
怎么提取日志？

**Comment by benzBrake** [comment]
https://user-images.githubusercontent.com/11323774/150891182-5d0ccc96-6405-4efa-88d1-867d1f00a2ea.mp4

**Comment by Justin62628** [comment]
请尝试退出后台的杀毒软件[捂脸]然后在库-属性-做文件完整性校验，可能有关键组件被杀了

**Comment by benzBrake** [comment]
> 

是被杀毒软件干掉了
