### ISSUE TITLE
有时会转换到100%时不停止继续从头转换，进度超出100%

### ISSUE THREAD

**Issue by jwy090815** [Justin62628/Squirrel-RIFE#325]
![搜狗截图20220208185721](https://user-images.githubusercontent.com/17699605/152974784-7595ce65-1658-4e92-a398-f1967a679c72.jpg)
文件转完了还不停止，之前挂机转换看到都显示400%了

**Comment by Justin62628** [comment]
这种是比较少见的正常情况，软件没办法识别输入视频的总帧数（全部解码一遍来判断帧数开销过大）有可能是因为输入视频封装不规范或者是动态帧率导致（vfr）

**Comment by jwy090815** [comment]
测试了一下，确实是动态帧率的问题，不知道能不能解决

**Comment by jwy090815** [comment]
> 这种是比较少见的正常情况，软件没办法识别输入视频的总帧数（全部解码一遍来判断帧数开销过大）有可能是因为输入视频封装不规范或者是动态帧率导致（vfr）
可以在转换之前判断是否为动态帧率，固定帧率就照常转换，动态帧率就先编码成固定帧率再转换或者把动态帧率导出成图片序列来编码放大，不知道还有什么好方法

**Comment by Justin62628** [comment]
如果识别到动态帧率后先编码成固定帧率或导出成图片序列都会耗费额外的时间（而且这处理也太像waifu2x-gui了就不太好hhh），我们应该会在之后出一个识别到动态帧率的提示
