### ISSUE TITLE
视频没有图像只有声音

### ISSUE THREAD

**Issue by xiaowu2001** [Justin62628/Squirrel-RIFE#332]
视频处理过程中预览窗口绿屏或者黑屏，最后结果也没有图像

**Comment by Justin62628** [comment]
请发送视频的mediainfo

**Comment by Justin62628** [comment]
以及使用的软件名称（这个仓库负责SVFI和SAE

**Comment by xiaowu2001** [comment]
视频部分的信息：
Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 135:134 DAR 120:67], 1591 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)

**Comment by xiaowu2001** [comment]
视频信息使用ffprobe查看。
![image](https://user-images.githubusercontent.com/98504541/153808798-5d98e750-0631-4f17-a5f4-cbeb4f067282.png)

SAE版本是0.0.3。硬件配置：i7-9750H, 16G RAM, GTX1650（驱动511.09）。

**Comment by xiaowu2001** [comment]
我尝试处理了一张图片，发现了同样的问题。
这是原图
![input](https://user-images.githubusercontent.com/98504541/155275921-15407177-5b16-46ed-9b9c-bc9ddfc5f4b7.png)
处理后在输出路径是这样
![00000000](https://user-images.githubusercontent.com/98504541/155275981-15550cdf-58a8-4052-9120-14f7e7c821d9.png)
输出的日志：
[2022-02-23.log](https://github.com/Justin62628/Squirrel-RIFE/files/8122515/2022-02-23.log)

**Comment by Justin62628** [comment]
![00000000](https://user-images.githubusercontent.com/37169106/159453638-091722b3-3f8d-4ac3-8533-1c77c0bf2cd7.png)
我使用我的20系显卡未能复现这个错误，这是使用Real CUGAN 2x模型超分的输出。根据ailab那边大佬的说法是驱动问题，请考虑更换驱动

**Comment by xiaowu2001** [comment]
> ![00000000](https://user-images.githubusercontent.com/37169106/159453638-091722b3-3f8d-4ac3-8533-1c77c0bf2cd7.png) 我使用我的20系显卡未能复现这个错误，这是使用Real CUGAN 2x模型超分的输出。根据ailab那边大佬的说法是驱动问题，请考虑更换驱动

应该是20系以下的显卡不支持半精度推理，我用Windows版的CUGAN只要把half改为false就不会出现这种错误了。
