### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Xiamo-vip** [Justin62628/Squirrel-RIFE#344]
[2022-03-12.error.log](https://github.com/Justin62628/Squirrel-RIFE/files/8237483/2022-03-12.error.log)

**Comment by Xiamo-vip** [comment]
显卡：gtx760 2g

**Comment by Xiamo-vip** [comment]
cpu i3 10105f

**Comment by Xiamo-vip** [comment]
内存8g 2666

**Comment by NULL204** [comment]
显卡是否支持CUDA？

**Comment by Justin62628** [comment]
尝试更新显卡驱动，如果还不行就说明GTX760过老，不受支持（最低支持是GTX750ti，但不排除特殊情况）
