### ISSUE TITLE
SAE怎么调用A卡进行超分？

### ISSUE THREAD

**Issue by KIrayamoto** [Justin62628/Squirrel-RIFE#401]
虽然软件提示了会使用核显或A卡，但是实际上调用的似乎是cpu

**Comment by Justin62628** [comment]
选择带有ncnn字样的模型或者waifu2x

**Comment by KIrayamoto** [comment]
> 选择带有ncnn字样的模型或者waifu2x
并没有找到有ncnn字样的模型

**Comment by Justin62628** [comment]
> 

那估计是还没整合[捂脸]先用waifu2x吧
