### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by semel1** [Justin62628/Squirrel-RIFE#402]
Hello, your software looks very impressive.
Unfortunately I do not know Chinese language.  
Do you plan to add English version (especially to your SFVI Professional  posted on STEAM
https://store.steampowered.com/app/1718750/SVFI__Professional ?

**Comment by Justin62628** [comment]
There is a Language Option in task bar, with English option
![image](https://user-images.githubusercontent.com/37169106/174721287-724e94fd-dd51-44ba-82bf-7f05cdd87f33.png)
