### ISSUE TITLE
Unable to utilize dGPU in Laptop ; only uses iGPU

### ISSUE THREAD

**Issue by Razor54672** [Justin62628/Squirrel-RIFE#410]
I ran the software and from Task Manager, it looks like it is not utilizing my laptop's RTX 3050 GPU and instead is solely relying on the CPU and iGPU. 

I have manually changed SAE.exe's settings in Windows to favor High Performance, aka dGPU, but it still doesn't seem to fix that.

Any solutions?

**Comment by Justin62628** [comment]
is GPU Selection available?
![image](https://user-images.githubusercontent.com/37169106/177158385-050d8210-e22b-4c8e-8030-7c703f38e3b0.png)
or anything like this?
If not I'm afraid it's more feasible to try out SVFI Demo on Steam
https://store.steampowered.com/app/1692080/SVFI/

**Comment by Razor54672** [comment]
I was using real-CUGAN and don't remember that option being there.
However, I think I did manage to force it to use dGPU by adding SAE.exe to High Performance setting in Windows Graphics.
