### ISSUE TITLE
问一下SAE 0.0.3 怎么走独显渲染啊

### ISSUE THREAD

**Issue by DavidLogic** [Justin62628/Squirrel-RIFE#411]
在软件中好像没有特殊的设置,建议增加一下

**Comment by Justin62628** [comment]
默认就是独显渲染，如果你发现cpu占用较高，那是因为prores编码也需要一定cpu资源；如果你发现是核显在跑，说明你选择的是ncnn模型且核显位置较前；
之后会添加选择显卡的设置

**Comment by DavidLogic** [comment]
Ok，谢谢
