### ISSUE TITLE
1440p Output Resoltion with realcugan

### ISSUE THREAD

**Issue by Razor54672** [Justin62628/Squirrel-RIFE#414]
I have a QHD laptop display and as such, upscaling 1080p video to 4K is a waste of space and more importantly, my GPU doesn't have enough memory to carry out the upscaling. 

Is there a way to edit it and add a QHD resolution setting? Or does it have to be an integral ratio?

**Comment by Justin62628** [comment]
There should be a custom resolution settings in the settings panel(the right one). You can enter your feasible resolution there.

**Comment by Justin62628** [comment]
sorry for late reply, try to swith "Output Resolution Preset" to "Custom" and you should be able to enter the resolution?

**Comment by Justin62628** [comment]
I'm closing this since there's no further comment
