### ISSUE TITLE
关于UI和默认设置以及选项描述的一些建议

### ISSUE THREAD

**Issue by 98mxr** [Justin62628/Squirrel-RIFE#416]
### 默认设置
1.我下载后第一次进SVFI后，默认设置和`载入默认设置`的设置选项并不一样，这可是新电脑。
2.`重复帧去除`的`单一识别`的值从`0.65`设为`0.5`。
3.BasicVSR系`超分序列长度`默认为5以上。
4.不必默认开启`高精度优化工作流`。

### UI排布
既然`导出带音频`、`导出带字幕`放在了`输出质量控制`，那么`输出图片序列`也应该放在那里，`输出质量控制`应改名为`输出控制`。
可以在`编码器`中加一个`PNG`。

### 选项描述
1.`补帧倍率`描述
![image](https://user-images.githubusercontent.com/82786769/179892130-858e2436-606f-4f55-9e49-e6e0de8e9a73.png)
**人话？**
现在已经不能这么设置了，全重写，请！

2.`重复帧去除`描述
![image](https://user-images.githubusercontent.com/82786769/179892439-de6c0e23-be80-4775-b57a-a43386a6d831.png)
`单一识别`的值应适应新的光流判断模式，请（佬写，需要增加帧分配相关描述，也请（佬写，但需警惕他不说人话。

3.`输出分辨率预设`
![image](https://user-images.githubusercontent.com/82786769/179892889-287376ad-e182-4b08-970d-b6a1be5f1523.png)
不要凭空捏造，请改成`8KUHD 8K 3840P`

**Comment by Justin62628** [comment]
SVFI 3.19.20-alpha
已更新除
> 既然`导出带音频`、`导出带字幕`放在了`输出质量控制`，那么`输出图片序列`也应该放在那里，`输出质量控制`应改名为`输出控制`。可以在`编码器`中加一个`PNG`。
以外的内容
导出音频、字幕，输出图片序列设置在首页保留
