### ISSUE TITLE
页面文件太小，无法完成操作

### ISSUE THREAD

**Issue by Minori-ty** [Justin62628/Squirrel-RIFE#418]
[导出设置预览]

任务参数预览：
SVFI版本：0.0.3
[基本信息]
输出文件夹：C:/Users/15638/Desktop/test 
输入帧率：25.00000 
输出帧率：50.00000 
输出格式：png 
导出带音频字幕：False
补帧倍率：1
风险模式：False
[工作状态恢复]
补帧时刻：00:00:00 - 00:00:00
起始区块：-1 起始输入帧：-1
[转场识别与动漫优化]
关闭转场识别：False 
转场识别参数：12 
转场使用帧混合：False 
输出转场帧：False
使用固定转场识别：False 
固定转场识别参数：40
重复帧去除模式：0
[输出分辨率]
宽：1000 高：743
黑边长度 - 宽：0 高：0
使用AI超分：True
使用的超分算法：realCUGAN
使用的超分模型：up4x-latest-denoise_3.pth
超分切割模式：200
超分切割块大小：200
超分半精度：True
超分转移分辨率模式：0
[输出质量控制]
渲染质量crf：16
目标码率：90.0
编码器：H265,8bit 
压制编码预设：fast 
N卡硬编预设：None
使用默认编码模式：False
高精度工作流：True
使用快速拆帧：False
HDR模式：0 
硬件解码：True 
指定编码线程数：False
开启反交错：False 
开启快速降噪：False
输出区块大小：1000 帧
手动指定缓冲区内存：1G
开启时间重映射：False 帧率 = fps
自定义压制参数：
[补帧参数]
半精度模式：False 
双向光流：True 
反向光流：False 
动态光流尺度：False
固定光流尺度：1.00
使用的补帧模型：
TTA：模式 = 0 代数 = 1
用于补帧的N卡：-1
使用NCNN补帧：True
NCNN补帧线程数：4
NCNN选择的GPU：0
使用多卡：False
N卡计数：0

app_dir => F:\SAE.0.0.3\Package
crop_height => 0
crop_width => 0
debug => False
encode_audio_checker => False
gif_loop => True
gui_inputs => {"inputs": [{"task_id": "359_958764", "input_path": "C:/Users/15638/Desktop/4a6421a4462309f7c66a524c650e0cf3d7cad611.jpg"}]}
hdr_cube_index => 0
hdr_mode => 0
input_end_point => 00:00:00
input_fps => 25.00000
input_start_point => 00:00:00
interp_start => -1
is_16bit_workflow => True
is_encode_audio => False
is_exp_prior => True
is_img_output => True
is_keep_head => False
is_no_scdet => False
is_output_only => True
is_quick_extract => False
is_render_slow_motion => False
is_rife_reverse => False
is_save_audio => False
is_scdet_mix => False
is_scdet_output => False
manual_buffer_size => 1
ncnn_gpu => 0
ncnn_thread => 4
no_concat => False
output_chunk_cnt => -1
output_dir => C:/Users/15638/Desktop/test
output_ext => png
pos => PyQt5.QtCore.QPoint(3, 33)
remove_dup_mode => 0
remove_dup_threshold => 10.0
render_bitrate => 90.0
render_crf => 16
render_encode_thread => 16
render_encoder => H265,8bit
render_encoder_preset => fast
render_ffmpeg_customized => 
render_gap => 1000
render_hwaccel_mode => CPU
render_hwaccel_preset => None
render_slow_motion_fps => 
resize_exp => 1.0
resize_height => 743
resize_settings_index => 0
resize_width => 1000
rife_cuda_cnt => 0
rife_exp => 1
rife_interlace_inference => 0
rife_interp_before_resize => 100
rife_model => 
rife_model_name => 
rife_scale => 1.00
rife_tta_iter => 1
rife_tta_mode => 0
risk_resume_mode => False
scdet_fixed_max => 40
scdet_flow_cnt => 0
scdet_mode => 0
scdet_threshold => 12
size => PyQt5.QtCore.QSize(589, 584)
sr_module_exp => 4
sr_realcugan_tilemode => 0
sr_tilesize => 200
sr_tilesize_mode => 0
target_fps => 50.00000
transfer_ratio_index => 0
use_bitrate => False
use_crf => True
use_dedup_sobel => False
use_deinterlace => False
use_evict_flicker => False
use_fast_denoise => False
use_hwaccel_decode => True
use_manual_buffer => False
use_manual_encode_thread => False
use_ncnn => True
use_realesr_fp16 => True
use_render_avx512 => False
use_render_encoder_default_preset => False
use_render_zld => False
use_rife_auto_scale => False
use_rife_forward_ensemble => True
use_rife_fp16 => False
use_rife_multi_cards => False
use_scdet_fixed => False
use_specific_gpu => -1
use_sr => True
use_sr_algo => realCUGAN
use_sr_mode => 0
use_sr_model => up4x-latest-denoise_3.pth
version => 0.0.3

[设置信息]

[Squirrel Anime Enhance 0.0.3 仅渲染操作启动]
2022-07-24 00:42:57,043 - one_line_shot_args - 241 - INFO - Initial New Interpolation Project: PROJECT DIR: C:/Users/15638/Desktop/test\4a6421a4462309f7c66a524c650e0cf3d7cad611_359_958764, INPUT FILEPATH: C:/Users/15638/Desktop/4a6421a4462309f7c66a524c650e0cf3d7cad611.jpg
2022-07-24 00:42:57,059 - one_line_shot_args - 149 - INFO - Render only, target fps is changed to input fps: 25.0
2022-07-24 00:42:57,059 - one_line_shot_args - 182 - INFO - Free RAM: 2.8G, Update Task Queue Len: 88, Duplicate Frames Cnt Upper Limit: 13
2022-07-24 00:42:57,059 - one_line_shot_args - 111 - INFO - Check Input Source: FPS: 25.0 -> 25.0, FRAMES_CNT: 0, INTERP_TIMES: 1, HDR: CUSTOM_HDR, FRAME_SIZE: (0, 0), QUEUE_LEN: 88, INPUT_EXT: , OUTPUT_EXT: .png
Traceback (most recent call last):
File "F:\SAE.0.0.3\Package\one_line_shot_args.py", line 2560, in <module>
File "F:\SAE.0.0.3\Package\one_line_shot_args.py", line 2231, in __init__
File "F:\SAE.0.0.3\Package\one_line_shot_args.py", line 1980, in __init__
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "F:\SAE.0.0.3\Package\SuperResolution\RealCUGANModule.py", line 4, in <module SuperResolution.RealCUGANModule>
File "F:\SAE.0.0.3\Package\torch\__init__.py", line 117, in <module>
raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "F:\SAE.0.0.3\Package orch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
INFO - ONE LINE SHOT ARGS 0.0.3 2022-07-24
Warning: Find Empty Arguments at 'render_ffmpeg_customized'
Warning: Find Empty Arguments at 'render_slow_motion_fps'
Warning: Find Empty Arguments at 'rife_model'
Warning: Find Empty Arguments at 'rife_model_name'

INFO - 2022-07-24 00:42:57.282428 C:/Users/15638/Desktop/4a6421a4462309f7c66a524c650e0cf3d7cad611.jpg 完成

**Comment by Minori-ty** [comment]
![4a6421a4462309f7c66a524c650e0cf3d7cad611](https://user-images.githubusercontent.com/79521943/180614626-da2f42d8-204f-4bfb-9fb7-563e43eec93e.jpg)

**Comment by YiWeiHuang-stack** [comment]
调整虚拟内存大小(另外建议不要调到C盘)

**Comment by Minori-ty** [comment]
> 调整虚拟内存大小(另外建议不要调到C盘)

在哪里调？我要调多少？

**Comment by YiWeiHuang-stack** [comment]
虚拟内存你百度一下就行，大概调个30720M
