### ISSUE TITLE
友链

### ISSUE THREAD

**Issue by Justin62628** [Justin62628/Squirrel-RIFE#419]
在steam论坛和qq群发布公告：
- [ ] 常见问题去steam论坛或者在[非官方论坛](https://bbs.svfi.xyz/)
- [ ] 要资源去非官方[SVFI-PT站](srvfi.top)

**Comment by NowLoadY** [comment]
非官方论坛提示发送邮箱失败

**Comment by Justin62628** [comment]
SVFI 3.19.23-alpha已添加友链
