### ISSUE TITLE
批量超分图片时(文件夹) 尺寸比例与原图不匹配

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [Justin62628/Squirrel-RIFE#422]
批量超分图片时，第二张图片开始后的所有图片与第一张图片输出尺寸相同，产生形变。
另外当原图过大时(例: 21640x13800)，在开启切割块与低显存模式下仍然会出现显存溢出的问题。
并且建议当检测到文件夹中图片尺寸不一时自动启用低显存模式，防止中途显存溢出(解决上一条问题的基础上)

**Comment by Justin62628** [comment]
- [x] 批量超分图片时，第二张图片开始后的所有图片与第一张图片输出尺寸相同，产生形变。SVFI 3.19.25-alpha修复
- [ ] 检测到文件夹中图片尺寸不一时自动启用低显存模式，防止中途显存溢出(解决上一条问题的基础上)
