### ISSUE TITLE
或许是一种实现绝对流畅的更优方法（仅任意时刻模型

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [Justin62628/Squirrel-RIFE#424]
[linear_timestep_generate.zip](https://github.com/Justin62628/Squirrel-RIFE/files/9253250/linear_timestep_generate.zip)
内含一个template.py模板（内含大体思路）
三种光流Implement(cv2, gmflow, raft) (极其不推荐使用cv2计算光流
gmflow.pth和raft.pth权重文件传不上来,复制gmflow-sintel，raft-sintel就行

**Comment by YiWeiHuang-stack** [comment]
以及通过对cv2，gmflow，raft计算的光流对比发现，cv2的光流可能极其不精确，或许当时用cv2算光流失败的转场识别，可以尝试用AI方法(gmflow,raft等)来做

**Comment by YiWeiHuang-stack** [comment]
注意三种实现代码中以下的两行
```
    # 计算timestep
    timestep_A = (num_frames_interpolate_A + 1) / 1
    timestep_B = (num_frames_interpolate_B + 1) / 1
```
应改成
```
    # 计算timestep
    timestep_A = 1 / (num_frames_interpolate_A + 1)
    timestep_B = 1 / (num_frames_interpolate_B + 1)
```

**Comment by YiWeiHuang-stack** [comment]
这是可直接使用的EISAI复现版本

https://drive.google.com/file/d/1TfB_06wBMbGGzCkR-V4vzvEPfyDK3Ga0/view?usp=sharing

**Comment by YiWeiHuang-stack** [comment]
目前发现的问题:
1.此方法对一拍二一拍三交替画面效果较差

**Comment by Justin62628** [comment]
See Implementations at [LinearTimestepTest.py](https://github.com/Justin62628/RIFE_GUI/blob/83b99a02680ddf3c21a0b5ddf318d5f7fd9d0195/DevUtils/Inference/LinearTimestepTest.py)
