### ISSUE TITLE
时间重映射功能缺少额外注释

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [Justin62628/Squirrel-RIFE#425]
当启用起始与结束补帧时刻时，时间重映射对应秒数不再精确

例如起始 00:00:23 结束 00:00:25
原视频24帧，输出帧率480，时间重映射30
期待输出32秒，实际输出22秒
其余片段秒数不等

从头开始，00:00:00 -> 00:00:02 不存在该问题

**Comment by Justin62628** [comment]
问题在于起始和结束补帧时刻使用的是不精确的定位方法，即使关闭风险模式也是如此
后续考虑加入精确定位的自定义片段时刻

**Comment by Justin62628** [comment]
起始结束补帧时刻和任务进度恢复冲突，后续不考虑精确定位的自定义片段时刻
