### ISSUE TITLE
高分屏适配

### ISSUE THREAD

**Issue by 185264646** [Justin62628/Squirrel-RIFE#432]
在高分屏下图标和文字显示太小，影响使用。

**Comment by Justin62628** [comment]
请问软件版本？

**Comment by 185264646** [comment]
> 请问软件版本以及问题截图？

版本：3.20.4
截图：
![图片](https://user-images.githubusercontent.com/43387518/184529428-72a715a5-1f67-457f-bf89-138ec8274cf1.png)
我开了200%缩放，但是明显这个软件的文字比浏览器的小了一半，没有遵从系统设置。

**Comment by YiWeiHuang-stack** [comment]
参考如下:

![(UFM72{H7F0`5S{Y9)SMSAR](https://user-images.githubusercontent.com/68835291/184529537-f00b656f-c98e-4794-a2a9-3ecb6662b6be.png)

![MB{GVL75OSO0W0 LRBL0M}Q](https://user-images.githubusercontent.com/68835291/184529541-98b864ae-3727-4b29-9769-b68ce93c5399.png)

**Comment by 185264646** [comment]
> 参考如下:
> 
> ![(UFM72{H7F0`5S{Y9)SMSAR](https://user-images.githubusercontent.com/68835291/184529537-f00b656f-c98e-4794-a2a9-3ecb6662b6be.png)
> 
> ![MB{GVL75OSO0W0 LRBL0M}Q](https://user-images.githubusercontent.com/68835291/184529541-98b864ae-3727-4b29-9769-b68ce93c5399.png)

这样设置确实可以，但是好像就是直接把程序界面拉伸到200%，字体和图标很糊，希望软件能够自己解决缩放问题。

**Comment by YiWeiHuang-stack** [comment]
后续会出全新的UI，有望解决该问题

**Comment by 185264646** [comment]
>
