### ISSUE TITLE
为什么没办法输出60帧

### ISSUE THREAD

**Issue by MarchBeta2087** [Justin62628/Squirrel-RIFE#433]
版本3.20.4
输出帧率一栏根本找不到
![QQ截图20220814151953](https://user-images.githubusercontent.com/98508270/184526721-066f3444-9ef8-45ff-97b2-68bb518b93b9.png)

**Comment by YiWeiHuang-stack** [comment]
这是SAE，专门超分辨率的软件，补帧要下SVFI

**Comment by MarchBeta2087** [comment]
> 这是SAE，专门超分辨率的软件，补帧要下SVFI

好的，我知道了
