### ISSUE TITLE
Squirrel Anime Enhance 3.20.4 打开闪退

### ISSUE THREAD

**Issue by xpirad** [Justin62628/Squirrel-RIFE#464]
纯英文路径
双击exe后显示加载页面 然后闪退
求助该如何解决！

**Comment by Justin62628** [comment]
使用[waifu2x-ext](https://github.com/AaronFeng753/Waifu2x-Extension-GUI)或使用正式版[svfi](https://steamcommunity.com/app/1692080)

**Comment by xpirad** [comment]
收到，谢谢您！
