### ISSUE TITLE
输出的图片可以重命名吗

### ISSUE THREAD

**Issue by NokiHaruka** [Justin62628/Squirrel-RIFE#472]
输出的图片名字都相同，需要自己手动改名，是否哪里能设置重命名。
输出的图片可以集中在一个目录，而不是分散的文件夹吗，没有找到相关的设置。

**Comment by Justin62628** [comment]
以后会实现输出到输入图片源文件夹这个功能

**Comment by NokiHaruka** [comment]
期待，作者加油！
