### ISSUE TITLE
设定起始结束补帧时刻后，选择导出字幕时支持切割字幕

### ISSUE THREAD

**Issue by yhrbjsy** [Justin62628/Squirrel-RIFE#490]
设定起始结束补帧时刻后，选择导出字幕时支持切割字幕

**Comment by Justin62628** [comment]
设定起始结束时刻的指定时间段功能仅用于测试。
绝大部分特殊字幕格式不支持无损切割。
为减轻软件依赖不会进一步引入第三方软件
