### ISSUE TITLE
一键补帧失败，返回码：1。请问这该怎么处理？

### ISSUE THREAD

**Issue by jrient** [Justin62628/Squirrel-RIFE#520]
[导出设置预览]

任务参数预览：
SVFI版本：3.20.4 
[基本信息]
输出文件夹：C:/data/squirrel 
输入帧率：60.00000 
输出帧率：60.00000 
输出格式：mp4 
导出带音频字幕：true
补帧倍率：1
风险模式：false
[工作状态恢复]
补帧时刻：00:00:00 - 00:00:00
起始区块：0 起始输入帧：0
[转场识别与动漫优化]
关闭转场识别：false 
转场识别参数：12 
转场使用帧混合：false 
输出转场帧：false
使用固定转场识别：false 
固定转场识别参数：20
重复帧去除模式：0
[输出分辨率]
宽：0 高：0
黑边长度 - 宽：0 高：0
使用AI超分：false
使用的超分算法：
使用的超分模型：
超分切割模式：0
超分切割块大小：400
超分半精度：false
超分转移分辨率模式：0
[输出质量控制]
渲染质量crf：16
目标码率：90
编码器：AUTO 
压制编码预设：AUTO 
N卡硬编预设：None
使用默认编码模式：false
高精度工作流：false
使用快速拆帧：false
HDR模式：0 
硬件解码：false 
指定编码线程数：false
开启反交错：false 
开启快速降噪：false
输出区块大小：1000 帧
手动指定缓冲区内存：1G
开启时间重映射：false 帧率 =  fps
自定义压制参数：
[补帧参数]
半精度模式：false 
绝对流畅：true
双向光流：true 
反向光流：false 
动态光流尺度：false
固定光流尺度：1.00
使用的补帧模型：
TTA：模式 = 0 迭代次数 = 1
用于补帧的显卡：0
使用NCNN补帧：false
NCNN补帧线程数：4
NCNN选择的GPU：0
使用多卡：false
N卡计数：

after_mission => 0
amd_card_cnt => 0
app_dir => C:\Users\jrient\DOWNLO~1\SAE320~1.4\Package
crop_height => 0
crop_width => 0
cuda_card_cnt => 0
debug => false
dumb_mode => true
dump_dir => 
encode_audio_checker => false
expert => true
gif_loop => false
gui_inputs => {"inputs": [{"task_id": "1f4_971430", "input_path": "C:/Users/jrient/Pictures/\u7d20\u6750/\u5f85\u53d1\u5e03/3\u670821\u65e5(1).mp4"}, {"task_id": "a0c_842240", "input_path": "C:/Users/jrient/Pictures/\u7d20\u6750/\u5f85\u53d1\u5e03/3\u670821\u65e5(2).mp4"}, {"task_id": "d7b_609065", "input_path": "C:/Users/jrient/Pictures/\u7d20\u6750/\u5f85\u53d1\u5e03/3\u670821\u65e5(3).mp4"}, {"task_id": "769_518707", "input_path": "C:/Users/jrient/Pictures/\u7d20\u6750/\u5f85\u53d1\u5e03/3\u670821\u65e5.mp4"}]}
hdr_cube_index => 0
hdr_mode => 0
input_end_point => 00:00:00
input_fps => 60.00000
input_start_point => 00:00:00
intel_card_cnt => 1
interp_start => 0
is_16bit_workflow => false
is_encode_audio => false
is_exp_prior => true
is_gui_quiet => false
is_img_output => false
is_keep_cache => false
is_keep_head => false
is_no_dedup_render => true
is_no_scdet => false
is_preview_args => false
is_preview_imgs => true
is_quick_extract => false
is_render_slow_motion => false
is_rife_reverse => false
is_rude_exit => true
is_safe_fps => true
is_save_audio => true
is_save_subs => true
is_scdet_mix => false
is_scdet_output => false
is_test_mode => false
is_windows_ontop => false
manual_buffer_size => 1
multi_task_rest => false
multi_task_rest_interval => 0
ncnn_gpu => 0
ncnn_thread => 4
no_concat => false
output_chunk_cnt => 0
output_dir => C:/data/squirrel
output_ext => mp4
pos => PyQt5.QtCore.QPoint(3, 33)
remove_dup_mode => 0
remove_dup_threshold => 0.2
render_bitrate => 90
render_crf => 16
render_encode_thread => 0
render_encoder => AUTO
render_encoder_preset => AUTO
render_ffmpeg_customized => 
render_gap => 1000
render_hwaccel_mode => AUTO
render_hwaccel_preset => None
render_slow_motion_fps => 
resize_exp => 0
resize_height => 0
resize_settings_index => 0
resize_width => 0
rife_exp => 1
rife_interlace_inference => 0
rife_interp_before_resize => 1000
rife_layer_connect_mode => 0
rife_scale => 1.00
rife_tta_iter => 1
rife_tta_mode => 0
rife_use_cpu => false
risk_resume_mode => false
scdet_fixed_max => 20
scdet_flow_cnt => 0
scdet_mode => 0
scdet_threshold => 12
size => PyQt5.QtCore.QSize(1242, 837)
sr_module_exp => 0
sr_ncnn_tta => false
sr_realcugan_alpha => 1
sr_realcugan_low_vram_mode => 0
sr_realcugan_tilemode => 0
sr_seq_len => 6
sr_tilesize => 400
sr_tilesize_mode => 0
svfi_preset => 2
target_fps => 60.00000
transfer_ratio_index => 0
use_bitrate => false
use_clear_inputs => false
use_crf => true
use_dedup_flow => false
use_dedup_sobel => false
use_deinterlace => false
use_evict_flicker => false
use_fast_denoise => false
use_global_settings => false
use_hwaccel_decode => false
use_manual_buffer => false
use_manual_encode_thread => false
use_ncnn => false
use_realesr_fp16 => false
use_render_avx512 => false
use_render_encoder_default_preset => false
use_render_zld => false
use_rife_auto_scale => false
use_rife_forward_ensemble => true
use_rife_fp16 => false
use_rife_multi_cards => false
use_scdet_fixed => false
use_sr => false
use_sr_algo => 
use_sr_gpu => 0
use_sr_mode => 0
use_sr_model => 
use_true_motion => true
use_vfi_gpu => 0
version => 3.20.4 
vfi_algo => AUTO
vfi_model => AUTO

[设置信息]

[3.20.4  补帧操作启动]
INFO: Find Empty Arguments at 'render_ffmpeg_customized'
INFO: Find Empty Arguments at 'render_slow_motion_fps'
INFO: Find Empty Arguments at 'use_sr_algo'
INFO: Find Empty Arguments at 'use_sr_model'
INFO: Find Empty Arguments at 'dump_dir'
2023-03-21 21:41:16,571 - ArgumentsModule - 619 - INFO - SAE OLS - 7.17.4, GUI - 3.20.4
2023-03-21 21:41:16,571 - ArgumentsModule - 621 - INFO - Initial New Interpolation Project: PROJECT DIR: C:/data/squirrel月21日(3)_d7b_609065, INPUT FILEPATH: C:/Users/jrient/Pictures/素材/待发布/3月21日(3).mp4
2023-03-21 21:41:16,683 - video - 588 - INFO - Auto Find FPS in r_frame_rate: 60.0
2023-03-21 21:41:17,362 - ArgumentsModule - 579 - INFO - Auto Sets HDR mode to NONE
2023-03-21 21:41:17,362 - ArgumentsModule - 579 - INFO - Auto Sets HDR mode to NONE
2023-03-21 21:41:17,363 - ArgumentsModule - 505 - INFO - To sync with the target fps, Update Render Gap (Chunk Size) to 960
2023-03-21 21:41:17,429 - ArgumentsModule - 526 - INFO - Free RAM: 7.9G, Update Task Queue Len: 24, Duplicate Frames Cnt Upper Limit: 31
2023-03-21 21:41:17,430 - ArgumentsModule - 361 - INFO - Check Input Source: FPS: 60.0 -> 60.0 -> 60.0, FRAMES_CNT: 558, INTERP_TIMES: 1, HDR: NONE, FRAME_SIZE: (1080, 1920), QUEUE_LEN: 24, INPUT_EXT: .mp4, OUTPUT_EXT: .mp4
Traceback (most recent call last):
File "C:\Users\jrient\DOWNLO~1\SAE320~1.4\Package\one_line_shot_args.py", line 682, in <module>
File "C:\Users\jrient\DOWNLO~1\SAE320~1.4\Package\one_line_shot_args.py", line 665, in run
File "C:\Users\jrient\DOWNLO~1\SAE320~1.4\Package\one_line_shot_args.py", line 193, in check_validation
File "C:\Users\jrient\DOWNLO~1\SAE320~1.4\Package\one_line_shot_args.py", line 164, in check_validate_functions
Exception: SAE: Frame Extraction and VFI Module Unavailable

INFO - 2023-03-21 21:41:17.509849 C:/Users/jrient/Pictures/素材/待发布/3月21日(3).mp4 完成

**Comment by Justin62628** [comment]
SAE仅用于超分
