### ISSUE TITLE
GUI界面添加段落补帧预览

### ISSUE THREAD

**Issue by NULL204** [Justin62628/Squirrel-RIFE#73]
添加分段补帧
一些补一些不补，区域可选，操作界面类似与Pr等剪辑软件（我到时候可以设计，也可以等我electron出来了以后再考虑）
只是一个想法，如果可以做最好，做不了也没关系
（别打我）

**Comment by Justin62628** [comment]
已经做好了，SVFI 3.x 高级选项-工作进度恢复-手动指定补帧时间区间00：00：00-00：00：00

**Comment by Justin62628** [comment]
预览功能筹备中

**Comment by NULL204** [comment]
我指的是更加易用的方法，操作更方便，不用手动输入，手拖进度条就好了

**Comment by NULL204** [comment]
到时候加载预览里面我觉得

**Comment by Justin62628** [comment]
预计SVFI 4.0 加入

**Comment by Justin62628** [comment]
预览整合到GUI内，而非独立于CLI

**Comment by NULL204** [comment]
我觉得其实预览方式要修改，现在的三段式太长

**Comment by NULL204** [comment]
![Uploading image.png…]()
我觉得这样会比较好其实

**Comment by Justin62628** [comment]
![image](https://user-images.githubusercontent.com/37169106/152141329-072cf6fe-3049-4f38-806b-e128120ded18.png)
比如右键单击的时候变成原画的样子

**Comment by Justin62628** [comment]
SVFI 3.14.2-alpha
开摆
