### ISSUE TITLE
建议开个wiki介绍详细操作技巧等

### ISSUE THREAD

**Issue by hyw-dev** [Justin62628/Squirrel-RIFE#88]

**Comment by Justin62628** [comment]
计划添加：
1. 对GIF补帧输出的压制操作（只提供压制gif的选项，不支持直接补帧gif）

**Comment by Justin62628** [comment]
[官方在线教程](doc.svfi.group)已上线
- [ ] 英文版同步更新
- [ ] 同步更新SVFI教程引导按钮

**Comment by Justin62628** [comment]
http://doc.svfi.group/
